apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-quarkus-pipeline
spec:
  project: simple-quarkus
  source:
    path: gitops-demo/simple-quarkus-service-deploy/tekton
    repoURL: https://github.com/froberge/simple-quarkus-service-deploy.git
    targetRevision: main
  destination:
    namespace: simple-quarkus-pipeline
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true