apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-quarkus-prod
spec:
  project: simple-quarkus
  source:
    path: gitops-demo/simple-quarkus-service-deploy/app/overlays/prod
    repoURL: https://github.com/froberge/simple-quarkus-service-deploy.git
    targetRevision: main
  destination:
    namespace: simple-quarkus-prod
    server: https://kubernetes.default.svc
  syncPolicy: {}