apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

bases:
  - ../../argocd-components/argocd-dev-instance

resources:
  - namespaces/simple-quarkus-dev.yaml
  - namespaces/simple-quarkus-prod.yaml
  - namespaces/simple-quarkus-pipeline.yaml
  - namespaces/rbac-developer.yaml
  #- tekton