apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: simple-quarkus-service-
spec:
  pipelineRef:
    name: simple-quarkus-service
  serviceAccountName: pipeline    
  params:
    - name: IMAGE_NAME
      value: image-registry.openshift-image-registry.svc:5000/pipeline-demo/simple-quarkus-service
    - name: APP_NAME
      value: simple-quarkus-service
    - name: GITHUB_REPO_URL
      value: https://github.com/froberge/simple-quarkus-service.git
    - name: GITHUB_REPO_REVISION
      value: main
    - name: PATH_CONTEXT
      value: .
    - name: VERSION
      value: openjdk-11-el7
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: sources-pvc
