apiVersion: v1
kind: Secret
metadata:
  name: github-authentication 
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: froberge
  password: ADD GITHUB TOKEN HERE
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline 
secrets:
  - name: github-authentication
...