apiVersion: v1
kind: Secret
metadata:
  name: github-authentication
  namespace: simple-quarkus-pipeline
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/basic-auth
stringData:
  username: froberge
  password: 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
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline 
secrets:
  - name: github-authentication
...