apiVersion: v1
kind: Secret
metadata:
  name: github-authentication
  namespace: simple-quarkus-pipeline
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: [Add your username]
  password: [GITHUB TOKEN]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline 
secrets:
  - name: github-authentication
...