apiVersion: v1
kind: Secret
metadata:
  name: github-authentication
  namespace: simple-quarkus-pipeline
  annotations:
    tekton.dev/git-0: github.com
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
  .git-credentials: |
    https://froberge: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@github.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline 
secrets:
  - name: github-authentication
...