apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simple-quarkus-dev


patchesJson6902:
- path: deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: simple-quarkus-service
    version: v1
resources:
- ../../base/