apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simple-quarkus-dev


patchesJson6902:
- path: deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: simple-quarkus-service
    version: v1
resources:
- ../../base/
images:
- name: image-registry.openshift-image-registry.svc:5000/simple-quarkus-pipeline/simple-quarkus-service
  newTag: dabfaa
