apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-quarkus-service
    app.openshift.io/runtime: quarkus
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "simple-quarkus-service:latest"
          },
          "fieldPath": "spec.template.spec.containers[?(@.name==\"simple-quarkus-service\")].image"
        }
      ]
  name: simple-quarkus-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-quarkus-service
  template:
    metadata:
      labels:
        app: simple-quarkus-service
    spec:
      containers:
        - name: simple-quarkus-service
          image: image-registry.openshift-image-registry.svc:5000/pipeline-demo-simple-quarkus/simple-quarkus-service:latest
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 5
status: {}