---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-quarkus-service
  name: simple-quarkus-service

spec:
  selector:
    app: simple-quarkus-service
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---