---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-quarkus-service
  name: simple-quarkus-service
  namespace: argocd-simple-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-quarkus-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-quarkus-service
    spec:
      containers:
      - image: quay.io/froberge/simple-quarkus-service:v4
        name: simple-quarkus-service
        resources: {}
---
