kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    deployment.kubernetes.io/revision: '1'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"simple-quarkus-service:v2","namespace":"froberge-dev"},"fieldPath":"spec.template.spec.containers[?(@.name==\"simple-quarkus-service\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '1237274220'
  name: simple-quarkus-service

  labels:
    app: simple-quarkus-service
    app.kubernetes.io/component: simple-quarkus-service
    app.kubernetes.io/instance: simple-quarkus-service
    app.kubernetes.io/name: simple-quarkus-service
    app.kubernetes.io/part-of: quarkus-app
    app.openshift.io/runtime: quarkus

spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-quarkus-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-quarkus-service
        deploymentconfig: simple-quarkus-service
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: simple-quarkus-service
          image: >-
            image-registry.openshift-image-registry.svc:5000/pipeline-demo-simple-quarkus/simple-quarkus-service
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
