apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simple-quarkus-pipeline

resources:
  - workspaces/maven-repo-pvc.yaml
  - workspaces/source-pvc.yaml
  - pipelines/simple-quarkus-service-gitops.yaml
  - pipelines/github-secret.yaml
  - pipelines/serviceaccount-yaml
  - task/set-image-tag.yaml
  - task/kustomize-task.yaml
  - triggers/github-eventlistener.yaml
  - triggers/github-pr-trigger-binding.yaml
  - triggers/listener-routes.yaml
  - triggers/simple-quarkus-service-trigger-template.yaml

