apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simple-quarkus-pipeline

resources:
  - workspaces/source-pvc.yaml
  - workspaces/maven-repo-pvc.yaml
  - pipelines/simple-quarkus-service-gitops.yaml
  - triggers/simple-quarkus-service-trigger-template.yaml
  - triggers/github-pr-trigger-binding.yaml
  - triggers/github-eventlistener.yaml
