apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pipeline-demo

resources:
  - namespace.yaml
  - workspaces/source-pvc.yaml
  - pipelines/simple-quarkus-service.yaml
  - triggers/simple-quarkus-service-trigger-template.yaml
  - triggers/github-pr-trigger-binding.yaml
  - triggers/github-eventlistener.yaml
  - app/deployment.yaml
  - app/service.yaml
  - app/route.yaml